
#ifndef MRCC_INTERFACE_H_
#define MRCC_INTERFACE_H_

typedef enum {
	AHB1_BUS,
	AHB2_BUS,
	APB1_BUS,
	APB2_BUS,
}System_Bus_t;
void MRCC_voidInit();
void MRCC_voidEnablePeripheral(System_Bus_t Copy_uddtBus,u8 Copy_u8Peripehral);
void MRCC_voidDisablePeripheral(System_Bus_t Copy_uddtBus,u8 Copy_u8Peripehral);


typedef enum
{
	AHB1_GPIOA=0,
	AHB1_GPIOB,
	AHB1_GPIOC,
	AHB1_GPIOD,
	AHB1_GPIOE,
	RESERVED1_AHB,
	RESERVED2_AHB,
	RESERVED3_AHB,
	RESERVED4_AHB,
	AHB1_CRCRST,
	RESERVED5_AHB,
	RESERVED6_AHB,
	RESERVED7_AHB,
	RESERVED8_AHB,
	RESERVED9_AHB,
	RESERVED10_AHB,
	RESERVED11_AHB,
	RESERVED12_AHB,
	RESERVED13_AHB,
	AHB1_DMA1,
	AHB1_DMA2,
}AHB1;
#define AHB2_OTGFS 7
typedef enum
{
	APB1_TIM2 = 0,
	APB1_TIM3,
	APB1_TIM4,
	APB1_TIM5,
    RESERVED1_APB1,
    RESERVED2_APB1,
    RESERVED3_APB1,
    RESERVED4_APB1,
    RESERVED5_APB1,
    RESERVED6_APB1,
    RESERVED7_APB1,
	APB1_WWDG,
    RESERVED8_APB1,
    RESERVED9_APB1,
	APB1_SPI2,
	APB1_SPI3,
    RESERVED10_APB1,
	APB1_USART2,
    RESERVED11_APB1,
    RESERVED12_APB1,
    RESERVED13_APB1,
	APB1_I2C1,
	APB1_I2C2,
	APB1_I2C3,
    RESERVED14_APB1,
    RESERVED15_APB1,
    RESERVED16_APB1,
    RESERVED17_APB1,
	APB1_PWR,
    RESERVED18_APB1,
    RESERVED19_APB1,
    RESERVED20_APB1
} APB1;

typedef enum
{
	APB2_TIM1 = 0,
	RESERVED1_APB2,
	RESERVED2_APB2,
	RESERVED3_APB2,
	APB2_USART1,
	APB2_USART6,
    RESERVED4_APB2,
	RESERVED5_APB2,
	APB2_ADC1,
    RESERVED6_APB2,
    RESERVED7_APB2,
	APB2_SDIO,
	APB2_SPI1,
	APB2_SPI4,
	APB2_SYSCFG,
    RESERVED8_APB2,
	APB2_TIM9,
	APB2_TIM10,
	APB2_TIM11,

} APB2;
#endif /* MRCC_INTERFACE_H_ */
